USE rideshare;

# ---- use once 
ALTER TABLE january_green ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE february_green ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE march_green ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE april_green ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE may_green ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE june_green ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE january_yellow ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE february_yellow ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE march_yellow ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE april_yellow ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE may_yellow ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE june_yellow ADD ride_id INT AUTO_INCREMENT PRIMARY KEY;
